Engine: jython
Engine Version: 2.7.0
Language: python
Language Version: 2.7

Jython
Error: failed to make directory: Z:/cycle/current/data/sics/reports/exp1298
IOError: [Errno 13] Permission denied: u'Z:/cycle/current/data/sics/reports/exp1298/LogFile.txt' in <script> at line number 36[2023-09-21 15:57:53] <Initialised> loaded
'[2023-09-21 15:57:53] <Initialised> loaded\n'
[2023-09-21 16:08:16] <Experiment Setup> loaded
'[2023-09-21 16:08:16] <Experiment Setup> loaded\n'
Traceback (most recent call last):
  File "<script>", line 114, in apply_values
NameError: global name 'slog' is not defined
New experiment created.
NameError: name '__newfile_enabled__' is not defined in <script> at line number 35[2023-09-21 16:11:46] <Taipan Live Data> loaded
'[2023-09-21 16:11:46] <Taipan Live Data> loaded\n'
NameError: name '__newfile_enabled__' is not defined in <script> at line number 35[2023-09-21 16:12:34] <Taipan Live Data> loaded
'[2023-09-21 16:12:34] <Taipan Live Data> loaded\n'
Traceback (most recent call last):
  File "<script>", line 1, in <module>
NameError: name '__run_script__' is not defined
Traceback (most recent call last):
  File "<script>", line 1, in <module>
NameError: name '__run_script__' is not defined
[2023-09-21 16:13:09] <Experiment Setup> loaded
'[2023-09-21 16:13:09] <Experiment Setup> loaded\n'
NameError: name '__newfile_enabled__' is not defined in <script> at line number 35[2023-09-21 16:13:13] <Taipan Live Data> loaded
'[2023-09-21 16:13:13] <Taipan Live Data> loaded\n'
[2023-09-21 16:13:34] <Batch Export> loaded
'[2023-09-21 16:13:34] <Batch Export> loaded\n'
NameError: name '__newfile_enabled__' is not defined in <script> at line number 35[2023-09-21 16:13:38] <Taipan Live Data> loaded
'[2023-09-21 16:13:38] <Taipan Live Data> loaded\n'
